### Feature Engineering

In [1]:
import pandas as pd
import numpy as np

In [2]:
df =pd.read_csv("student_data.csv")

In [3]:
df.head(10)

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,4,3,4,1,1,3,6,5,6,6
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,5,3,3,1,1,3,4,5,5,6
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,4,3,2,2,3,3,10,7,8,10
3,GP,F,15,U,GT3,T,4,2,health,services,...,3,2,2,1,1,5,2,15,14,15
4,GP,F,16,U,GT3,T,3,3,other,other,...,4,3,2,1,2,5,4,6,10,10
5,GP,M,16,U,LE3,T,4,3,services,other,...,5,4,2,1,2,5,10,15,15,15
6,GP,M,16,U,LE3,T,2,2,other,other,...,4,4,4,1,1,3,0,12,12,11
7,GP,F,17,U,GT3,A,4,4,other,teacher,...,4,1,4,1,1,1,6,6,5,6
8,GP,M,15,U,LE3,A,3,2,services,other,...,4,2,2,1,1,1,0,16,18,19
9,GP,M,15,U,GT3,T,3,4,other,other,...,5,5,1,1,1,5,0,14,15,15

In [4]:
df.dtypes

school        object
sex           object
age            int64
address       object
famsize       object
Pstatus       object
Medu           int64
Fedu           int64
Mjob          object
Fjob          object
reason        object
guardian      object
traveltime     int64
studytime      int64
failures       int64
schoolsup     object
famsup        object
paid          object
activities    object
nursery       object
higher        object
internet      object
romantic      object
famrel         int64
freetime       int64
goout          int64
Dalc           int64
Walc           int64
health         int64
absences       int64
G1             int64
G2             int64
G3             int64
dtype: object

In [5]:
categorical = df.select_dtypes(include = "object")
numerical = df.select_dtypes(include =["int64","float64"])

In [6]:
categorical.columns

Index(['school', 'sex', 'address', 'famsize', 'Pstatus', 'Mjob', 'Fjob',
       'reason', 'guardian', 'schoolsup', 'famsup', 'paid', 'activities',
       'nursery', 'higher', 'internet', 'romantic'],
      dtype='object')

In [7]:
numerical.columns

Index(['age', 'Medu', 'Fedu', 'traveltime', 'studytime', 'failures', 'famrel',
       'freetime', 'goout', 'Dalc', 'Walc', 'health', 'absences', 'G1', 'G2',
       'G3'],
      dtype='object')

In [8]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df["sex"] = le.fit_transform(df["sex"])

In [9]:
df["sex"].head()

0    0
1    0
2    0
3    0
4    0
Name: sex, dtype: int64

In [10]:
le.classes_

array(['F', 'M'], dtype=object)

In [11]:
df["school"] = le.fit_transform(df["school"])

In [12]:
df["school"].head(10)

0    0
1    0
2    0
3    0
4    0
5    0
6    0
7    0
8    0
9    0
Name: school, dtype: int64

In [13]:
le.classes_

array(['GP', 'MS'], dtype=object)

In [14]:
df["address"] = le.fit_transform(df["address"])

In [15]:
df["address"].head()

0    1
1    1
2    1
3    1
4    1
Name: address, dtype: int64

In [16]:
le.classes_

array(['R', 'U'], dtype=object)

In [17]:
df["higher"] = le.fit_transform(df["higher"])

In [18]:
df["higher"].head()

0    1
1    1
2    1
3    1
4    1
Name: higher, dtype: int64

In [19]:
le.classes_

array(['no', 'yes'], dtype=object)

In [20]:
df["internet"] = le.fit_transform(df["internet"])

In [21]:
df["internet"].head()

0    0
1    1
2    1
3    1
4    0
Name: internet, dtype: int64

In [22]:
le.classes_

array(['no', 'yes'], dtype=object)

In [23]:
df["romantic"] = le.fit_transform(df["romantic"])

In [24]:
df["romantic"].head()

0    0
1    0
2    0
3    1
4    0
Name: romantic, dtype: int64

In [25]:
le.classes_

array(['no', 'yes'], dtype=object)

In [26]:
categorical = df.select_dtypes(include="object")

print("Number of categorical columns:", categorical.shape[1])
print(categorical.columns)

Number of categorical columns: 11
Index(['famsize', 'Pstatus', 'Mjob', 'Fjob', 'reason', 'guardian', 'schoolsup',
       'famsup', 'paid', 'activities', 'nursery'],
      dtype='object')

In [27]:
numerical = df.select_dtypes(include=["int64", "float64"])

print("Number of numerical columns:", numerical.shape[1])
print(numerical.columns)

Number of numerical columns: 22
Index(['school', 'sex', 'age', 'address', 'Medu', 'Fedu', 'traveltime',
       'studytime', 'failures', 'higher', 'internet', 'romantic', 'famrel',
       'freetime', 'goout', 'Dalc', 'Walc', 'health', 'absences', 'G1', 'G2',
       'G3'],
      dtype='object')

In [28]:
for column in df.select_dtypes(include="object").columns:
    if df[column].nunique() == 2:
        df[column] = le.fit_transform(df[column])

In [29]:
df.dtypes

school         int64
sex            int64
age            int64
address        int64
famsize        int64
Pstatus        int64
Medu           int64
Fedu           int64
Mjob          object
Fjob          object
reason        object
guardian      object
traveltime     int64
studytime      int64
failures       int64
schoolsup      int64
famsup         int64
paid           int64
activities     int64
nursery        int64
higher         int64
internet       int64
romantic       int64
famrel         int64
freetime       int64
goout          int64
Dalc           int64
Walc           int64
health         int64
absences       int64
G1             int64
G2             int64
G3             int64
dtype: object

In [30]:
df.to_csv("student_encoded.csv", index=False)

In [31]:
df["Mjob"].unique()

array(['at_home', 'health', 'other', 'services', 'teacher'], dtype=object)

In [32]:
df = pd.get_dummies(df,columns=["Mjob", "Fjob", "reason", "guardian"],dtype=int)

In [33]:
df.head()

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,traveltime,studytime,...,Fjob_other,Fjob_services,Fjob_teacher,reason_course,reason_home,reason_other,reason_reputation,guardian_father,guardian_mother,guardian_other
0,0,0,18,1,0,0,4,4,2,2,...,0,0,1,1,0,0,0,0,1,0
1,0,0,17,1,0,1,1,1,1,2,...,1,0,0,1,0,0,0,1,0,0
2,0,0,15,1,1,1,1,1,1,2,...,1,0,0,0,0,1,0,0,1,0
3,0,0,15,1,0,1,4,2,1,3,...,0,1,0,0,1,0,0,0,1,0
4,0,0,16,1,0,1,3,3,1,2,...,1,0,0,0,1,0,0,1,0,0

In [34]:
df.dtypes

school               int64
sex                  int64
age                  int64
address              int64
famsize              int64
Pstatus              int64
Medu                 int64
Fedu                 int64
traveltime           int64
studytime            int64
failures             int64
schoolsup            int64
famsup               int64
paid                 int64
activities           int64
nursery              int64
higher               int64
internet             int64
romantic             int64
famrel               int64
freetime             int64
goout                int64
Dalc                 int64
Walc                 int64
health               int64
absences             int64
G1                   int64
G2                   int64
G3                   int64
Mjob_at_home         int64
Mjob_health          int64
Mjob_other           int64
Mjob_services        int64
Mjob_teacher         int64
Fjob_at_home         int64
Fjob_health          int64
Fjob_other           int64
Fjob_services        int64
Fjob_teacher         int64
reason_course        int64
reason_home          int64
reason_other         int64
reason_reputation    int64
guardian_father      int64
guardian_mother      int64
guardian_other       int64
dtype: object

In [35]:
df.select_dtypes(include="object").columns

Index([], dtype='object')

In [36]:
df.to_csv("student_final.csv", index=False)

In [37]:
df.shape

(395, 46)

In [38]:
"Mjob" in df.columns

False

In [39]:
[col for col in df.columns if col.startswith("Mjob_")]

['Mjob_at_home', 'Mjob_health', 'Mjob_other', 'Mjob_services', 'Mjob_teacher']